CREATE TABLE IF NOT EXISTS firm (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firm_name VARCHAR(255) UNIQUE NOT NULL,
  gst_no VARCHAR(15) UNIQUE NOT NULL,
  firm_city VARCHAR(100) NOT NULL,
  firm_street VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_firm_name (firm_name),
  INDEX idx_gst_no (gst_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;