
CREATE TABLE IF NOT EXISTS ORDERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_date DATE NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  invoice_no VARCHAR(50) UNIQUE NOT NULL,
  order_status ENUM('PENDING', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
  payment_status ENUM('UNPAID', 'PARTIALLY_PAID', 'PAID') NOT NULL DEFAULT 'UNPAID',
  delivery_status ENUM('PENDING', 'PARTIALLY_DELIVERED', 'DELIVERED') NOT NULL DEFAULT 'PENDING',
  firm_id INT NOT NULL,
  customer_id INT NOT NULL,
  created_by INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE RESTRICT,
  FOREIGN KEY (firm_id) REFERENCES firm(id) ON DELETE RESTRICT,
  FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT,
  INDEX idx_order_date (order_date),
  INDEX idx_firm_id (firm_id),
  INDEX idx_customer_id (customer_id),
  CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;